Add more tooling

diff --git a/template/Makefile.toml.liquid b/template/Makefile.toml.liquid
--- a/template/Makefile.toml.liquid
+++ b/template/Makefile.toml.liquid
@@ -1,5 +1,52 @@
-[tasks.dev]
+[tasks.init]
+script=```
+    echo # installing git hooks
+    pre-commit --version || pip install pre-commit
+    pre-commit install || echo "failed to install git hooks!" 1>&2
+    echo # things required for `cargo make test`
+    cargo install cargo-nextest --no-confirm
+    echo # things required by `cargo make pre-commit`
+    cargo install cargo-spellcheck --no-confirm
+    echo # things required by `cargo make coverage`
+    rustup component add llvm-tools-preview
+    cargo install cargo-llvm-cov --no-confirm
+    echo # things required by `cargo make audit`
+    cargo install cargo-audit --no-confirm
+```
+
+[tasks.test]
 env = { "RUST_LOG" = "info" }
 command = "cargo"
-args = ["run"]
-watch = true
+args = ["nextest", "run", "${@}"]
+
+[tasks.test-ci]
+env = { "RUST_LOG" = "info", "RUN_MODE" = "ci" }
+command = "cargo"
+args = ["nextest", "run" "--all-features"]
+
+[tasks.docs]
+command = "cargo"
+args = ["doc", "--no-deps", "--all-features", "--document-private-items", "--examples"]
+
+[tasks.coverage]
+command = "cargo"
+args = ["llvm-cov", "${@}"]
+
+[tasks.audit]
+command = "cargo"
+args = ["audit"]
+
+[tasks.timings]
+script=```
+    cargo clean
+    cargo build --release --quiet --timings
+    xdg-open /target/cargo-timings/cargo-timing.html
+```
+
+[tasks.pre-commit]
+script=```
+    cargo make test
+    cargo make docs
+    cargo spellcheck fix
+    cargo spellcheck reflow
+```
